version: "3.7"

services:
  db:
    container_name: db-container
    image: postgres:15.2
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./data:/data/db
    ports:
      - "5432:5432"
  app:
    container_name: app-container
    image: node:18
    restart: always
    working_dir: /usr/softpet/
    command: bash -c "npm install && npx prisma migrate dev && npm run dev"
    volumes:
      - .:/usr/softpet
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/softpet?schema=public
    ports:
      - "3000:3000"
    links:
      - db
    logging:
      options:
        max-size: 10m
        max-file: "3"